"""updated user mapping phone no

Revision ID: 1b7e13efc4db
Revises: 8ebf60b96bb9
Create Date: 2024-09-21 17:32:17.364744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b7e13efc4db'
down_revision = '8ebf60b96bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_spam_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=50), nullable=True))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_spam_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
