"""added user_id in user_session table

Revision ID: 8ebf60b96bb9
Revises: b71c8acf2120
Create Date: 2024-09-21 03:12:24.021733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebf60b96bb9'
down_revision = 'b71c8acf2120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
